//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sapper2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sapper2.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag.
        /// </summary>
        public static string AppBar_Button_flag {
            get {
                return ResourceManager.GetString("AppBar_Button_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string AppBar_Button_pause {
            get {
                return ResourceManager.GetString("AppBar_Button_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        public static string AppBar_Button_restart {
            get {
                return ResourceManager.GetString("AppBar_Button_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBar_MenuItem_About {
            get {
                return ResourceManager.GetString("AppBar_MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the most addictive puzzle game now redesigned for Windows Phone!.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Label_Author {
            get {
                return ResourceManager.GetString("Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me.
        /// </summary>
        public static string Label_ContactMe {
            get {
                return ResourceManager.GetString("Label_ContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Other Apps.
        /// </summary>
        public static string Label_MyOtherApps {
            get {
                return ResourceManager.GetString("Label_MyOtherApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate This App.
        /// </summary>
        public static string Label_RateThisApp {
            get {
                return ResourceManager.GetString("Label_RateThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brutal.
        /// </summary>
        public static string Level_Brutal {
            get {
                return ResourceManager.GetString("Level_Brutal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Level_Easy {
            get {
                return ResourceManager.GetString("Level_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Level_Hard {
            get {
                return ResourceManager.GetString("Level_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Level_Medium {
            get {
                return ResourceManager.GetString("Level_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Hard.
        /// </summary>
        public static string Level_VeryHard {
            get {
                return ResourceManager.GetString("Level_VeryHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best time: .
        /// </summary>
        public static string Overlay_BestTime {
            get {
                return ResourceManager.GetString("Overlay_BestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string Overlay_Button_MainMenu {
            get {
                return ResourceManager.GetString("Overlay_Button_MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Overlay_Button_Restart {
            get {
                return ResourceManager.GetString("Overlay_Button_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Overlay_Button_Resume {
            get {
                return ResourceManager.GetString("Overlay_Button_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time: .
        /// </summary>
        public static string Overlay_TextBlock_YourTime {
            get {
                return ResourceManager.GetString("Overlay_TextBlock_YourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        public static string OverlayGameOver_Title {
            get {
                return ResourceManager.GetString("OverlayGameOver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string OverlayPause_Title {
            get {
                return ResourceManager.GetString("OverlayPause_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New best time!.
        /// </summary>
        public static string OverlayVictory_newBestTime {
            get {
                return ResourceManager.GetString("OverlayVictory_newBestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory!.
        /// </summary>
        public static string OverlayVictory_Title {
            get {
                return ResourceManager.GetString("OverlayVictory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Name.
        /// </summary>
        public static string ViewCustomLevel_LevelName {
            get {
                return ResourceManager.GetString("ViewCustomLevel_LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board: .
        /// </summary>
        public static string ViewCustomLevel_Textblock_Board {
            get {
                return ResourceManager.GetString("ViewCustomLevel_Textblock_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ViewCustomLevel_Textblock_Color {
            get {
                return ResourceManager.GetString("ViewCustomLevel_Textblock_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string ViewCustomLevel_Textblock_Horizontal {
            get {
                return ResourceManager.GetString("ViewCustomLevel_Textblock_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Count.
        /// </summary>
        public static string ViewCustomLevel_Textblock_MineCount {
            get {
                return ResourceManager.GetString("ViewCustomLevel_Textblock_MineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mines: .
        /// </summary>
        public static string ViewCustomLevel_Textblock_Mines {
            get {
                return ResourceManager.GetString("ViewCustomLevel_Textblock_Mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string ViewCustomLevel_Textblock_Vertical {
            get {
                return ResourceManager.GetString("ViewCustomLevel_Textblock_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom level.
        /// </summary>
        public static string ViewCustomLevel_Title {
            get {
                return ResourceManager.GetString("ViewCustomLevel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minesweeper.
        /// </summary>
        public static string ViewMainPage_ApplicationTitle {
            get {
                return ResourceManager.GetString("ViewMainPage_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom levels.
        /// </summary>
        public static string ViewMainPage_CustomLevelsHeader {
            get {
                return ResourceManager.GetString("ViewMainPage_CustomLevelsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mines.
        /// </summary>
        public static string ViewMainPage_TextBlock_mines {
            get {
                return ResourceManager.GetString("ViewMainPage_TextBlock_mines", resourceCulture);
            }
        }
    }
}
